### ISSUE TITLE
获取不到  hystrix 配置

### ISSUE THREAD

**Issue by whw188** [tigerMoon/demo-hystrix-config#1]
//节点信息
        String nodeProperty = DynamicPropertyFactory.getInstance()
                .getStringProperty("config", "<none>")
                .get();

这一步获取的一直是 默认值， <none> 

是我使用的方式不对吗

**Comment by tigerMoon** [comment]
你有创建节点吗？
// 创建节点，数据存储在节点上，nodecache
create path /myapp/config "hystrix.command.ExampleKey.execution.isolation.thread.timeoutInMilliseconds=4000"

**Comment by whw188** [comment]
create path /myapp/config "hystrix.command.ExampleKey.execution.isolation.thread.timeoutInMilliseconds=4000"                 这个不能带   双引号，         README.md中              去掉双引号 就可以了
